version: '3'

env:
  NATS_URL: http://localhost:4222/ 

tasks:
  up-infra:
    desc: "Start infrastructure services (NATS, etc.)"
    cmds:
      - docker-compose -f deploy/docker-compose.infra.yaml up -d

  down-infra:
    desc: "Stop infrastructure services"
    cmds:
      - docker-compose -f deploy/docker-compose.infra.yaml down

  up-apps:
    desc: "Start application services (gateway, etc.)"
    cmds:
      - docker-compose -f deploy/docker-compose.apps.yaml up -d