version: "3"

env:

tasks:
  tf:init:
    desc: "Initialize Terraform in the infrastructure directory"
    cmds:
      - terraform -chdir=deploy/terraform init

  tf:plan:
    desc: "Plan Terraform changes in the infrastructure directory"
    cmds:
      - terraform -chdir=deploy/terraform plan

  tf:apply:
    desc: "Apply Terraform changes in the infrastructure directory"
    cmds:
      - terraform -chdir=deploy/terraform apply -auto-approve
  
  tf:apply:local:
    desc: "Apply Terraform changes using local state (for development)"
    cmds:
      - terraform -chdir=deploy/terraform apply -auto-approve -var="gateway_internal_host=http://host.docker.internal:8080" {{.CLI_ARGS}}

  docker:logs:
    desc: "View logs for all services"
    cmds:
      - docker-compose -f deploy/docker-compose.infra.yaml logs -f
      - docker-compose -f deploy/docker-compose.apps.yaml logs -f

  docker:up:
    desc: "Start all services (infrastructure and applications)"
    cmds:
      - task: docker:up-infra
      - task: docker:up-apps

  docker:down:
    desc: "Stop all services (infrastructure and applications)"
    cmds:
      - task: docker:down-infra
      - task: docker:down-apps

  docker:up-infra:
    desc: "Start infrastructure services (NATS, etc.)"
    cmds:
      - docker-compose -f deploy/docker-compose.infra.yaml up -d

  docker:down-infra:
    desc: "Stop infrastructure services"
    cmds:
      - docker-compose -f deploy/docker-compose.infra.yaml down

  docker:up-apps:
    desc: "Start application services (gateway, etc.)"
    cmds:
      - docker-compose -f deploy/docker-compose.apps.yaml up -d

  docker:down-apps:
    desc: "Stop application services"
    cmds:
      - docker-compose -f deploy/docker-compose.apps.yaml down

  docker:destroy:
    desc: "Stop and remove all containers, networks, volumes, and images"
    prompt: "This will remove all containers, networks, volumes, and images. Are you sure?"
    cmds:
      - docker-compose -f deploy/docker-compose.infra.yaml down --volumes --remove-orphans
      - docker-compose -f deploy/docker-compose.apps.yaml down --volumes --remove-orphans