events { worker_connections 1024; }

http {
    # Точка входа для самого Authentik (Админка и интерфейсы)
    server {
        listen 80;
        server_name authentik.local;

        location / {
            proxy_pass http://server:9000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # Точка входа для вашего Дашборда
    server {
        listen 80;
        server_name dash.zero-dashboard.local;

        location / {
            proxy_pass http://server:9000; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}