services:
  gateway:
    image: reputation/gateway:latest
    container_name: gateway
    build:
      context: ..
      dockerfile: services/go/gateway/Dockerfile
    networks:
      - zero-dashboard
    environment:
      - NATS_URL=nats://nats:4222

networks:
  zero-dashboard:
    external: true # network defined in docker-compose.infra.yaml