services:
  server:
    command: server
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
    - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.5.3}
    restart: unless-stopped
    shm_size: 512mb
    networks:
      - zero-dashboard
    volumes:
    - ./data:/data
    - ./custom-templates:/templates
  worker:
    command: worker
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
    - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.5.3}
    restart: unless-stopped
    shm_size: 512mb
    user: root
    networks:
      - zero-dashboard
    volumes:
    - ./data:/data
    - ./certs:/certs
    - ./custom-templates:/templates
  authentik_proxy:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/proxy}:${AUTHENTIK_TAG:-2026.5.3}
    environment:
        AUTHENTIK_HOST: http://server:9000
        AUTHENTIK_INSECURE: "true"
        AUTHENTIK_TOKEN: ${AUTHENTIK_OUTPOST_TOKEN:-}
        # Optional setting to be used when `authentik_host` for internal communication doesn't match the public URL.
        # AUTHENTIK_HOST_BROWSER: http://authentik.local
    ports:
      - "9000:9000"
    networks:
      - zero-dashboard
volumes:
  database:
    driver: local
