### ENV
@host = http://localhost:8080
@token = akadmin_token_xyz123


# Test Telegram webhook with valid payload
POST {{host}}/v1/webhooks/telegram/SECRET_TOKEN_CAFE_452
Content-Type: application/json

{
  "payload": {
    "customer": {
      "platform_user_id": "tg_user_998231",
      "phone": "+79991234567",
      "name": "Иван Иванов"
    },
    "message": {
      "message_id": "msg_88231",
      "text": "Принесли холодный суп, официант хамил!",
      "raw_rating": 2
    }
  }
}